### ISSUE TITLE
Leaking/performance issues when adding/removing from tree

### ISSUE THREAD

**Issue by ccnokes** [LottieFiles/lottie-react#48]
## Overview

If the Player is added/removed from the tree, something internally is leaking and it can cause the animation to jank and then the page to crash. 

See this sandbox: https://codesandbox.io/s/confident-booth-unplv?file=/src/App.tsx

Click the toggle button once. Everything works and the animation shows. Click it twice and it might be a bit slower. 3-4+ times (at least on my computer) it slows to a crawl and the page becomes unresponsive. 

## Labels

- [ ] Add the `Type: Bug` label to this issue.

**Comment by karamalie** [comment]
Hi @ccnokes 
It looks like this is because there are repeaters in the animation. They add up with each load up of the instance.
Please try passing in the json object as a string to the src prop. 
JSON.stringify(animationData) and pass it into the src. 

https://codesandbox.io/s/zealous-elgamal-kk6gp?file=/src/App.tsx
